### PR TITLE
Client UI structure

### PR DESCRIPTION
**Pull request by gdcho**
https://www.loom.com/share/a50c6edc5533487b8dbd1d9027ea912b?sid=d49c912c-fcd6-4702-8822-c5569d68c0dd

### CODE REVIEW

**Comment by gdcho** [comment]
will change typescript type on refractors after calling in api

**Review by jasper-oh — APPROVED** [review]
So remain work would be
1) Manage Card ( Edit, Delete, Card) page
2) Use Ajax for retrieve data with API ?

And I think we should ask to instructor about ajax is the mandatory

**Comment by gdcho** [comment]
yup, still need to finish manage card for admin, auth for login, and api

**Comment by jasper-oh** [comment]
Hmm let me wor the game part with API. (Loom video  20 sec ~ 46 sec)

Can you work on the Manage card for admin - just UI part?

If you are ok w/ this, we can close this pr and merge it

Nice job btw

**Comment by gdcho** [comment]
did you want me to work on manage part on this pr? 
I was going to call it a day for tonight

**Comment by jasper-oh** [comment]
Sorry for confusion, I mean close this pr and work on the Manage card page for admin tmr.

Let's close this pr and merge this

**Pull request merged**
