### PR TITLE
[Feat] Client server WebSocket blueprint with chat

### PR DESCRIPTION
**Pull request by jasper-oh**
Server - Open the endpoint "ws://localhost:8081/api/game-room"
Client - Create Basic UI and "HOW TO USE" flow

### CODE REVIEW

**Comment by jasper-oh** [comment]
Why vercel hate my code F!

**Review by gdcho — APPROVED** [review]
lgtm, will update specs and design over the long weekend

**Comment by gdcho** [comment]
image

**Comment by gdcho** [comment]
npm run build error - would be good practice to build before raising or

**Comment by jasper-oh** [comment]
> npm run build error - would be good practice to build before raising or

hold on is that mean we should run build before create the pr?

**Comment by jasper-oh** [comment]
ahhh I see I think my useWebSocket hook didn't commit

**Comment by gdcho** [comment]
> > npm run build error - would be good practice to build before raising or
> 
> 
> 
> hold on is that mean we should run build before create the pr?
> 
> 

yeah to make sure if there are no errors. just for good practice

**Pull request merged**
